package com.example.myapplication.Info;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import android.os.Parcel;
import android.os.Parcelable;
import android.support.annotation.Nullable;
import android.text.TextUtils;

import java.util.HashMap;


public class CompanyInfo implements Parcelable {

    private static final String KEY_COM_ID="comid";
    private static final String KEY_EM_ID ="Emid";
    private static final String KEY_COM_FULL_NAME ="orgname";
    private static final String KEY_COM_NAME ="comname";
    private static final String KEY_ORG_ID ="orgid";
    private static final String KEY_ORG_ID_STR ="orgidstr";

    private static final String SEPARATOR = "##";

    private String mComId;
    private String mEmid;
    private String mComFullName;
    private String mComName;
    private String mOrgId;
    private String mOrgIdstr;

    private CompanyInfo() {
    }

    protected CompanyInfo(Parcel in) {
        mComId = in.readString();
        mEmid = in.readString();
        mComFullName = in.readString();
        mComName = in.readString();
        mOrgId = in.readString();
        mOrgIdstr = in.readString();
    }

    public static final Creator<CompanyInfo> CREATOR = new Creator<CompanyInfo>() {
        @Override
        public CompanyInfo createFromParcel(Parcel in) {
            return new CompanyInfo(in);
        }

        @Override
        public CompanyInfo[] newArray(int size) {
            return new CompanyInfo[size];
        }
    };

    public String getComId() {
        return mComId;
    }


    public String getEmid() {
        return mEmid;
    }


    public String getComFullName() {
        return mComFullName;
    }


    public String getComName() {
        return mComName;
    }


    public String getOrgId() {
        return mOrgId;
    }


    public String getOrgIdstr() {
        return mOrgIdstr;
    }

    @Override
    public String toString() {
        return mComId +
                SEPARATOR +
                mEmid +
                SEPARATOR +
                mComFullName +
                SEPARATOR +
                mComName +
                SEPARATOR +
                mOrgId +
                SEPARATOR +
                mOrgIdstr;
    }

    public static CompanyInfo fromString(String saveString) throws Exception {
        if(TextUtils.isEmpty(saveString)){
            throw new IllegalArgumentException("字符串为空");
        }
        String[] params = saveString.split(SEPARATOR);
        if(params.length<6){
            throw new IllegalArgumentException("传入的不是CompanyInfo的数据");
        }
        CompanyInfo companyInfo = new CompanyInfo();
        companyInfo.mComId = params[0];
        companyInfo.mEmid = params[1];
        companyInfo.mComFullName = params[2];
        companyInfo.mComName = params[3];
        companyInfo.mOrgId = params[4];
        companyInfo.mOrgIdstr = params[5];
        return companyInfo;
    }

    @Nullable
    public static CompanyInfo fromData(HashMap<String, Object> result) throws Exception {
        if(result==null || result.isEmpty()){
            return null;
        }
        CompanyInfo info =new CompanyInfo();
        info.mComId = (String) result.get(KEY_COM_ID);
        info.mEmid = (String) result.get(KEY_EM_ID);
        info.mComFullName = (String) result.get(KEY_COM_FULL_NAME);
        info.mComName = (String) result.get(KEY_COM_NAME);
        info.mOrgId = (String) result.get(KEY_ORG_ID);
        info.mOrgIdstr = (String) result.get(KEY_ORG_ID_STR);
        return info;
    }

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel parcel, int i) {
        parcel.writeString(mComId);
        parcel.writeString(mEmid);
        parcel.writeString(mComFullName);
        parcel.writeString(mComName);
        parcel.writeString(mOrgId);
        parcel.writeString(mOrgIdstr);
    }
}
